### ISSUE TITLE
Ordered comparison between pointer and zero ('char *' and 'int') error

### ISSUE THREAD

**Issue by iThinker** [tat/mimetic#5] opened 2017-09-29 16:45 UTC
Clang 4 produces this error in mmfile.cxx line 60.

**Comment by teusbenschop** [comment] 2017-10-31 13:04
The same error occurs here on macOS High Sierra.

```
mmfile.cxx:60:14: error: ordered comparison between pointer and zero ('char *' and 'int')
```

The line 
```if(m_beg > 0)```
was changed to 
```if(m_beg > (char *)0)```
and now it compiles.

**Comment by fake666** [comment] 2017-11-16 12:46
i think checking for nullptr is nicer. i didn't bother creating a pull request, fix:

https://github.com/fake666/mimetic/commit/34c7e9563cbcab004d43d9a150361ca10715cc5a

merged in my fork

**Comment by teusbenschop** [comment] 2017-11-16 12:58
Thanks man!

**Comment by radoslawkojdecki** [comment] 2018-11-16 15:27
man mmap:

"Upon successful completion, mmap() returns a pointer to the mapped region.  Otherwise, a value of MAP_FAILED is returned and errno is set to indicate the error. "

MAP_FAILED is mapped to -1, not nullptr !!!

**Comment by heirecka** [comment] 2021-03-07 12:55
gcc11 started to produce an error about that, too:
```
mmfile.cxx: In member function 'bool mimetic::MMFile::map()':
mmfile.cxx:60:14: error: ordered comparison of pointer with integer zero ('char*' and 'int')
   60 |     if(m_beg > 0)
      |        ~~~~~~^~~
```

**Comment by heirecka** [comment] 2021-03-07 13:00
After writing the comment above I realized that the problem is already fixed by bf84940f. So, sorry for the noise and I guess this issue can be closed.

**Comment by tat** [comment] 2021-04-12 07:00
yeah, thanks for looking into it anyway!

**Closed as completed by tat** 2021-04-12 07:01 UTC
